#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>

typedef struct {
    char head;
    char** body;
    int body_count;
} ProductionRule;

typedef struct {
    ProductionRule* rules;
    char* terminals;
    char start_symbol;
    int rule_count;
    int terminal_count;
} CFG;

ProductionRule* findRule(CFG* grammar, char symbol) {
    for (int i = 0; i < grammar->rule_count; i++) {
        if (grammar->rules[i].head == symbol) {
            return &(grammar->rules[i]);
        }
    }
    return NULL;
}

void generatePalindrome(CFG* grammar, char symbol, char* result, int* index) {
    if (strchr(grammar->terminals, symbol) != NULL) {
        result[(*index)++] = symbol;
    } else {
        ProductionRule* rule = findRule(grammar, symbol);
        if (rule != NULL) {
            int randomIndex = rand() % rule->body_count;
            for (int i = 0; rule->body[randomIndex][i] != '\0'; i++) {
                generatePalindrome(grammar, rule->body[randomIndex][i], result, index);
            }
        }
    }
}

bool parseString(CFG* grammar, const char* string, char symbol) {
    if (string[0] == '\0') {
        return true;
    }

    if (strchr(grammar->terminals, symbol) != NULL) {
        return string[0] == symbol && parseString(grammar, string + 1, symbol);
    } else {
        ProductionRule* rule = findRule(grammar, symbol);
        if (rule != NULL) {
            for (int i = 0; i < rule->body_count; i++) {
                if (parseString(grammar, string, rule->body[i][0])) {
                    return true;
                }
            }
        }
    }
    return false;
}

int main() {
    srand(time(NULL));

    CFG grammar;
    ProductionRule rules[2];
    char terminals[] = {'a', 'b', 'c', 'd', 'e', 'f'};
    char* rule_bodies_s[] = {"aSa", "bSb", "cSc", "dSd", "eSe", "fSf", "a", "b", "c", "d", "e", "f", NULL};
    char* rule_bodies_v[] = {"aSa", "bSb", "cSc", "dSd", "eSe", "fSf", "a", "b", "c", "d", "e", "f", NULL};

    // Initialize rules and grammar
    rules[0].head = 'S';
    rules[0].body = rule_bodies_s;
    rules[0].body_count = 12;
    
    rules[1].head = 'V';
    rules[1].body = rule_bodies_v;
    rules[1].body_count = 12;

    grammar.rules = rules;
    grammar.rule_count = 2;
    grammar.terminals = terminals;
    grammar.terminal_count = 6;
    grammar.start_symbol = 'S';

    printf("The CFG is initialized.\n");

    // Generate and parse palindrome
    char palindrome[256];
    int index = 0;
    generatePalindrome(&grammar, grammar.start_symbol, palindrome, &index);
    palindrome[index] = '\0'; // Null-terminate the string

    printf("Random Palindrome: %s\n", palindrome);

    if (parseString(&grammar, palindrome, grammar.start_symbol)) {
        printf("The string is a palindrome generated by the CFG.\n");
    } else {
        printf("The string is not a palindrome generated by the CFG.\n");
    }

    return 0;
}
